<template>
  <Navbar/>
  <ToastMessage/>
  <Loading :active="loadingStatus">
    <div class="loadingio-spinner-double-ring-l13lkhupya">
      <div class="ldio-lah3zelnfs">
        <div></div>
        <div></div>
        <div><div></div></div>
        <div><div></div></div>
      </div>
    </div>
  </Loading>

  <RouterView v-slot="{ Component }">
    <transition
      name="fade-transform"
      mode="out-in"
      enter-from-class="fade-transform-enter"
    >
      <component :is="Component"> </component>
    </transition>
  </RouterView>

  <Footer/>
</template>


<style lang="scss" scoped>
.fade-transform-leave-active,
.fade-transform-enter-active {
  transition: all 0.4s;
}

.fade-transform-enter {
  opacity: 0;
  transform: translateX(-30px);
}

.fade-transform-leave-to {
  opacity: 0;
  transform: translateX(30px);
}

/*loading style changed  generated by https://loading.io/ */
@keyframes ldio-lah3zelnfs {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-lah3zelnfs div { box-sizing: border-box!important }
.ldio-lah3zelnfs > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 12px solid #000;
  border-color: #e15b64 transparent #e15b64 transparent;
  animation: ldio-lah3zelnfs 1s linear infinite;
}

.ldio-lah3zelnfs > div:nth-child(2), .ldio-lah3zelnfs > div:nth-child(4) {
  width: 116px;
  height: 116px;
  top: 42px;
  left: 42px;
  animation: ldio-lah3zelnfs 1s linear infinite reverse;
}
.ldio-lah3zelnfs > div:nth-child(2) {
  border-color: transparent #f8b26a transparent #f8b26a
}
.ldio-lah3zelnfs > div:nth-child(3) { border-color: transparent }
.ldio-lah3zelnfs > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-lah3zelnfs > div:nth-child(3) div:before, .ldio-lah3zelnfs > div:nth-child(3) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 12px;
  height: 12px;
  top: -12px;
  left: 54px;
  background: #e15b64;
  border-radius: 50%;
  box-shadow: 0 132px 0 0 #e15b64;
}
.ldio-lah3zelnfs > div:nth-child(3) div:after {
  left: -12px;
  top: 54px;
  box-shadow: 132px 0 0 0 #e15b64;
}

.ldio-lah3zelnfs > div:nth-child(4) { border-color: transparent; }
.ldio-lah3zelnfs > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-lah3zelnfs > div:nth-child(4) div:before, .ldio-lah3zelnfs > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 12px;
  height: 12px;
  top: -12px;
  left: 40px;
  background: #f8b26a;
  border-radius: 50%;
  box-shadow: 0 104px 0 0 #f8b26a;
}
.ldio-lah3zelnfs > div:nth-child(4) div:after {
  left: -12px;
  top: 40px;
  box-shadow: 104px 0 0 0 #f8b26a;
}
.loadingio-spinner-double-ring-l13lkhupya {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-lah3zelnfs {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-lah3zelnfs div { box-sizing: content-box; }
/* <-- loading style changed end.--> */
</style>


<script>
import Navbar from "@/components/NavbarFront.vue";
import Footer from "@/components/Footer.vue";
import emitter from "@/methods/mitt";
import ToastMessage from "@/components/ToastMessage.vue";


export default {
  data() {
    return {
      loadingStatus: false,
    };
  },
  components: {
    Navbar,
    Footer,
    ToastMessage,
  },
  methods: {},
  mounted() {
    emitter.on("loading", () => {
      this.loadingStatus = true;
    });
    emitter.on("un-loading", () => {
      this.loadingStatus = false;
    });
  },
};
</script>